### ISSUE TITLE
Count all thumbs ups?

### ISSUE THREAD

**Issue by hadley** [jimhester/tidyversedashboard#30]
https://github.com/r-dbi/bigrquery/issues/361 — has 10 in total, but only 6 listed on dashboard.

**Comment by jimhester** [comment]
This is strange we are already querying `totalCount`, which you would think would get the total count, not the max

https://github.com/tidyverse/tidyversedashboard/blob/b589b82461e8520ef39a35f8114f8a4c5ff2ef8c/inst/issues.graphql#L9

**Comment by hadley** [comment]
I guess some people thumbsed-up more than once, but that still doesn't explain the discrepancy. It sounds like there's nothing we can do :(

**Comment by jimhester** [comment]
Oh wait, I guess that would be the number of separate reactions per issue, but the individual reactions each are only one. I don't see an obvious way to get what we want unfortunately.
