### ISSUE TITLE
Add org(s) logo(s)

### ISSUE THREAD

**Issue by maelle** [jimhester/tidyversedashboard#4]
I'll make a PR building on

```r 
#' Get org logo
#'
#' @param org 
#'
#' @return Path to logo
#' @export
#'
#' @examples
#' get_org_logo("lockedata")
get_org_logo <- function(org){
  glue::glue("https://github.com/{org}.png") %>%
  magick::image_read() %>%
    magick::image_resize("48x48") %>%
    magick::image_write("logo.png")
}
```

when there are several orgs the logo could be a collage but it might be a bit complicated and it'd be too small anyway... the docs could state the first logo is used. 💅

**Comment by jimhester** [comment]
Closed by https://github.com/jimhester/tidyversedashboard/pull/5
